/**
 * Shared labels and metadata for run timeline events.
 * Used by RunTimeline component and project dashboard Critiques section.
 */

export const phaseLabels: Record<string, string> = {
  'phase.extraction.started': 'Extracting Claims',
  'phase.evidence_discovery.started': 'Searching for Evidence',
  'phase.evidence_assessment.started': 'Assessing Evidence',
  'phase.review.started': 'Running Model Reviews',
  'phase.critique.started': 'Cross-Critiquing Reviews',
  'phase.critique_response.started': 'Responding to Critiques',
  'phase.revision.started': 'Revising Idea',
  'phase.consensus.started': 'Building Consensus',
  'phase.gap_detection.started': 'Detecting Evidence Gaps',
  'phase.gap_detection.completed': 'Gap Analysis Done',
  'phase.gap_detection.failed': 'Gap Detection Failed',
  'phase.goal_evaluation.started': 'Evaluating Goal Achievement',
  'phase.goal_evaluation.completed': 'Goal Evaluation Done',
  'phase.goal_evaluation.failed': 'Goal Evaluation Failed',
  'phase.extraction.completed': 'Claims Extracted',
  'phase.evidence_discovery.completed': 'Evidence Discovery Done',
  'phase.evidence_assessment.completed': 'Assessment Finished',
  'phase.review.completed': 'Reviews Collected',
  'phase.critique.completed': 'Critiques Complete',
  'phase.critique_response.completed': 'Critique Responses Done',
  'phase.revision.completed': 'Idea Revised',
  'phase.consensus.completed': 'Consensus Reached',
  'phase.adversarial_probe.started': 'Running Adversarial Probe',
  'phase.adversarial_probe.completed': 'Adversarial Probe Done',
  'phase.adversarial_probe.claim_probed': 'Claim Probed',
  'phase.consensus.evidence_gap_noted': 'Evidence Gap (Not Blocking)',
  'phase.consensus.evidence_floor_failed': 'Evidence Floor Failed (Blocked)',
  'phase.extraction.failed': 'Extraction Failed',
  'phase.discovery.failed': 'Discovery Failed',
  'phase.assessment.failed': 'Assessment Failed',
  'phase.review.failed': 'Review Failed',
  'phase.critique.failed': 'Critique Failed',
  'phase.critique_response.failed': 'Critique Response Failed',
  'phase.revision.failed': 'Revision Failed',
  'phase.consensus.failed': 'Consensus Failed',
  'critique.created': 'New Critique',
  'critique.responded': 'Critique Response',
  'idea.revised': 'Idea Revised',
  'idea.version_advanced': 'Version Advanced',
  'review.context_requested': 'Model Requested More Context',
  'iteration.started': 'Iteration Started',
  'iteration.completed': 'Iteration Completed',
  'iteration.failed': 'Iteration Failed',
  'goal.not_achieved': 'Goal Not Yet Achieved',
};
